# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b5e59c189b7ec74855c7a4e5f8bfdbb4244ea61e246cd1f975758db581a54d7da4cdb960f8dd082fbf218c669bcd6b570de6261016429454225ee2a8244a61b

test:
  secret_key_base: 02cdc2a8973a0469db097176d17f1aac1e128ae1344b6d04418a8ec0cdd614bc08bf4cde44d38fc0f5eab123b60932f91b81953017efe1866255f662ebefed45

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
